version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: accenture_app
      POSTGRES_PASSWORD: accenture
      POSTGRES_DB: accenture
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"
  transaction-application:
    container_name: transaction-application
    build:
      dockerfile: Dockerfile
    depends_on:
      - 'db'
    environment:
      DB_URL: db
    ports:
      - "8080:8080"

