spring:
  datasource:
    transactions:
      driver-class-name: "org.postgresql.Driver"
      username: "accenture_app"
      password: "accenture"
      url: "jdbc:postgresql://${DB_URL}:5432/accenture"
logging:
  pattern:
    console: "[%level] %d{yyyy-MM-dd HH:mm:ss} %X{requestId} - %logger{36} - %msg%n"

